# Build Stage
FROM golang:1.21-alpine AS builder
WORKDIR /app

# Dependency Caching
COPY go.mod go.sum ./
RUN go mod download

# Build
COPY . .
# Build the binary statically
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/proxy cmd/proxy/main.go

# Runtime Stage (Distroless / Scratch)
FROM scratch
COPY --from=builder /bin/proxy /bin/proxy
# Copy CA certificates for HTTPS calls
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/bin/proxy"]